version: '2.2'
volumes:
  redis-data:
networks:
  internal:
    driver: bridge
  consul-network:
    external:
      name: docker-compose-ha-consul-vault-ui_internal
services:
  redis:
    image: redis:6.0-alpine
    init: true
    command:
      - /bin/sh
      - -exc
      - |
        export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        IP="$$(awk '/32 host/ && f ~ /172.16.238/ { print f; exit }; {f=$$2}' /proc/net/fib_trie)"
        apk add curl
        consul-agent.sh --consul-host consul.service.consul --advertise "$$IP" --service '{"service": {"name": "redis", "port": 3306, "meta": {"title": "Redis", "description": "Redis in-memory key-value database.", "version": "'"$$(redis-server --version --version)"'"}}}'
        redis-server --appendonly yes
    expose:
      - 6379
    networks:
      - internal
      - consul-network
    dns:
      - 172.16.238.2
      - 172.16.238.3
    volumes:
      - redis-data:/data
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/consul:/usr/local/bin/consul:ro
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/jq:/usr/local/bin/jq:ro
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/scripts/consul-agent.sh:/bin/consul-agent.sh:ro
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/scripts/vault-functions.sh:/usr/local/share/vault-functions.sh:ro
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/vault:/usr/local/bin/vault:ro
